### ISSUE TITLE
可否将传入组件的其他props也一并传到textarea中？

### ISSUE THREAD

**Issue by uuid1017** [teambition/react-lite-textbox#8]
textarea的高度使用autosize进行设置，但是默认的高度太高了，需要将textarea的rows设置为1，不过本组件并没有给设置rows的入口，方便的话可以调整下吗

**Comment by uuid1017** [comment]
找到了minHeight，thx

**Comment by uuid1017** [comment]
最好还是把 “...props” 加上吧，还有绑定blur事件之类的需求

**Comment by Boshen** [comment]
@Edward67 你好， 简聊内部已经不再使用该组件， 现在使用的是https://github.com/andreypopp/react-textarea-autosize。
